// // Mocks generated by Mockito 5.2.0 from annotations
// // in ah_test/test/features/artifact_list/presentation/cubit/artifact_list_cubit_test.dart.
// // Do not manually edit this file.

// // @dart=2.9

// import 'package:ah_test/features/artifact_list/domain/usecases/get_artifacts_usecase.dart'
//     as _i2;
// import 'package:mockito/mockito.dart' as _i1;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types

// /// A class which mocks [GetArtifactsUsecase].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockGetArtifactsUsecase extends _i1.Mock
//     implements _i2.GetArtifactsUsecase {
//   MockGetArtifactsUsecase() {
//     _i1.throwOnMissingStub(this);
//   }
// }
